name: Angular PR Review

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - uses: reviewdog/action-setup@v1

      # Run ESLint
      - name: Run ESLint
        run: |
          npx eslint "src/**/*.{ts,html}" \
          -f checkstyle \
          -o eslint-result.xml
        continue-on-error: true

      # If file empty create dummy
      - name: Ensure result file
        run: |
          if [ ! -f eslint-result.xml ]; then
            echo '<?xml version="1.0"?><checkstyle></checkstyle>' > eslint-result.xml
          fi

      # Reviewdog
      - name: Run Reviewdog
        run: |
          reviewdog -f=checkstyle \
            -name="angular-review" \
            -reporter=github-pr-check \
            -level=warning \
            < eslint-result.xml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
